"""Product migration

Revision ID: 1f181c76ea51
Revises: 
Create Date: 2025-11-10 12:31:57.815021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f181c76ea51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_product_Management_id'), table_name='product_Management')
    op.drop_table('product_Management')
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_table('attendances')
    op.add_column('products', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('price', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('description', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('image', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('stock', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock')
    op.drop_column('products', 'image')
    op.drop_column('products', 'description')
    op.drop_column('products', 'category')
    op.drop_column('products', 'price')
    op.drop_column('products', 'name')
    op.create_table('attendances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('attendances_pkey'))
    )
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    op.create_table('product_Management',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('product_Management_pkey')),
    sa.UniqueConstraint('email', name=op.f('product_Management_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_product_Management_id'), 'product_Management', ['id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('product_pkey')),
    sa.UniqueConstraint('email', name=op.f('product_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    # ### end Alembic commands ###
