"""initial migration

Revision ID: 51fd95824dc4
Revises: 6717d08d51c9
Create Date: 2025-11-10 20:45:44.294134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51fd95824dc4'
down_revision: Union[str, None] = '6717d08d51c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('carts', sa.Column('order_id', sa.Integer(), nullable=False))
    op.add_column('carts', sa.Column('created_at', sa.String(length=100), nullable=False))
    op.add_column('carts', sa.Column('updated_at', sa.String(length=100), nullable=False))
    op.drop_constraint(op.f('carts_Order_id_fkey'), 'carts', type_='foreignkey')
    op.drop_constraint(op.f('carts_Product_id_fkey'), 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'carts', 'orders', ['order_id'], ['id'])
    op.drop_column('carts', 'Order_id')
    op.drop_column('carts', 'Product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('Product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('carts', sa.Column('Order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(op.f('carts_Product_id_fkey'), 'carts', 'products', ['Product_id'], ['id'])
    op.create_foreign_key(op.f('carts_Order_id_fkey'), 'carts', 'orders', ['Order_id'], ['id'])
    op.drop_column('carts', 'updated_at')
    op.drop_column('carts', 'created_at')
    op.drop_column('carts', 'order_id')
    op.drop_column('carts', 'product_id')
    # ### end Alembic commands ###
