"""todo migration

Revision ID: 5c4b0575bba3
Revises: de5964218e77
Create Date: 2025-11-11 12:47:44.858235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4b0575bba3'
down_revision: Union[str, None] = 'de5964218e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('todos', sa.Column('description', sa.String(length=100), nullable=False))
    op.add_column('todos', sa.Column('created_at', sa.String(length=100), nullable=False))
    op.add_column('todos', sa.Column('updated_at', sa.String(length=100), nullable=False))
    op.add_column('todos', sa.Column('due_date', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'due_date')
    op.drop_column('todos', 'updated_at')
    op.drop_column('todos', 'created_at')
    op.drop_column('todos', 'description')
    op.drop_column('todos', 'title')
    # ### end Alembic commands ###
