"""order migration

Revision ID: 6717d08d51c9
Revises: 1f181c76ea51
Create Date: 2025-11-10 17:30:11.590944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6717d08d51c9'
down_revision: Union[str, None] = '1f181c76ea51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('items', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('total_amount', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('status', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('shipping_address', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'items')
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###
